Build and sign macOS, try 194

diff --git a/.github/workflows/macos-compile-installer-release.yml b/.github/workflows/macos-compile-installer-release.yml
--- a/.github/workflows/macos-compile-installer-release.yml
+++ b/.github/workflows/macos-compile-installer-release.yml
@@ -4,9 +4,9 @@ name: macOS Build Installer with Version
 
 on:
   push:
-    branches: [ "buildSignMacOS" ]
-    #tags:
-      #- 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
+    #branches: [ "buildSignMacOS" ]
+    tags:
+      - 'v*'  # Build the app for commits that are tagged starting with 'v' e.g. v1.2.3
       # to tag a commit, use "git tag v1.2.3"
       # when you then use "git push origin v1.2.3" this workflow will be invoked
 #  workflow_dispatch:
@@ -31,16 +31,16 @@ jobs:
           echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
         shell: bash
 
-#      - name: Validate version format
-#        run: |
-#          echo ${VERSION}
-#          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-#            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
-#            exit 1
-#          fi
-#        shell: bash
-#      - name: Build version ${{ env.VERSION }}
-#      - uses: actions/checkout@v4
+      - name: Validate version format
+        run: |
+          echo ${VERSION}
+          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
+            exit 1
+          fi
+        shell: bash
+      - name: Build version ${{ env.VERSION }}
+      - uses: actions/checkout@v4
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
