Build and sign macOS, try 193

diff --git a/.github/workflows/macos-compile-installer-release.yml b/.github/workflows/macos-compile-installer-release.yml
--- a/.github/workflows/macos-compile-installer-release.yml
+++ b/.github/workflows/macos-compile-installer-release.yml
@@ -31,14 +31,14 @@ jobs:
           echo "FULL_VERSION=${FULL_VERSION}" >> $GITHUB_ENV
         shell: bash
 
-      - name: Validate version format
-        run: |
-          echo ${VERSION}
-          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
-            exit 1
-          fi
-        shell: bash
+#      - name: Validate version format
+#        run: |
+#          echo ${VERSION}
+#          if [[ ! "${VERSION}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+#            echo "Error: Version format is incorrect. It should match N.N.N where N is an integer."
+#            exit 1
+#          fi
+#        shell: bash
 #      - name: Build version ${{ env.VERSION }}
 #      - uses: actions/checkout@v4
       - name: Set up JDK 17
